//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app
//

import InAppPurchaseKit
import NotifKit
import OfficeKit
import SharedKit
import SupabaseKit
import SwiftUI

struct ContentView: View {

	init() {

	}

	var body: some View {
		TabView {

			Tab("Office", systemImage: "building.2") {
				OfficeView()
			}

			Tab("Calls", systemImage: "phone") {
				CallsView()
			}

			// Pre-made Settings View for easy native-looking settings screen.
			Tab("Settings", systemImage: "gear") {
				SettingsView()
			}

			#if DEBUG

				TabSection("DEBUG ONLY") {
					// Use this to create quick settings and toggles to streamline the development process
					Tab("Developer", systemImage: "hammer") {
						DeveloperSettingsView()
					}
				}

			#endif
		}

		.tabViewStyle(.sidebarAdaptable)
		.tabViewSidebarHeader {
			Text("Deskmates")
				.font(.title)
				.bold()
				.frame(maxWidth: .infinity, alignment: .leading)

		}

	}
}

#Preview {
	ContentView()
		.environmentObject(InAppPurchases())
}
